/// Flutter icons AppIcons
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.

library;

import 'dart:io';

import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData fairtrade = IconData(
    0xe800,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData organic = IconData(
    0xe801,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData veganVegetarian = IconData(
    0xe802,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mug = IconData(
    0xe803,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData milkshake = IconData(
    0xe804,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData cup = IconData(
    0xe805,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData starHalfFill = IconData(
    0xe806,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData starFill = IconData(
    0xe807,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData star = IconData(
    0xe808,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData profileId = IconData(
    0xe809,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData package = IconData(
    0xe80a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData returnIcon = IconData(
    0xe80b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData creditCard = IconData(
    0xe80c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData refund = IconData(
    0xe80d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData electricity = IconData(
    0xe80e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData animals = IconData(
    0xe80f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData microwave = IconData(
    0xe810,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData wifi = IconData(
    0xe811,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData glamping = IconData(
    0xe812,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData camper = IconData(
    0xe813,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rv = IconData(
    0xe814,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData caravan = IconData(
    0xe815,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tent = IconData(
    0xe816,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData fastDelivery = IconData(
    0xe817,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData alertFill = IconData(
    0xe818,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData help = IconData(
    0xe819,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData loading = IconData(
    0xe81a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData grid2Fill = IconData(
    0xe81b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData grid3 = IconData(
    0xe81c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData grid1Fill = IconData(
    0xe81d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData grid_2 = IconData(
    0xe81e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData exit = IconData(
    0xe81f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData settings = IconData(
    0xe820,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData refine = IconData(
    0xe821,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData delete = IconData(
    0xe822,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData notification = IconData(
    0xe823,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData search = IconData(
    0xe824,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData bagFill = IconData(
    0xe825,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData bag = IconData(
    0xe826,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData accountFill = IconData(
    0xe827,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData account = IconData(
    0xe828,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData wishlistFill = IconData(
    0xe829,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData wishlist = IconData(
    0xe82a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData menuAlt = IconData(
    0xe82b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData menu = IconData(
    0xe82c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData homeFill = IconData(
    0xe82d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData home = IconData(
    0xe82e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData download = IconData(
    0xe82f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData add = IconData(
    0xe830,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData _shareIOS = IconData(
    0xe831,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData _shareAndroid = IconData(
    0xe832,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static IconData get share {
    if (Platform.isIOS || Platform.isMacOS) {
      return _shareIOS;
    }
    return _shareAndroid;
  }

  static const IconData _backIOS = IconData(
    0xe833,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData _backAndroid = IconData(
    0xe844,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );

  static IconData get back {
    if (Platform.isAndroid) {
      return _backAndroid;
    }
    return _backIOS;
  }

  static const IconData forward = IconData(
    0xe834,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData chevronRight = IconData(
    0xe835,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData chevronLeft = IconData(
    0xe836,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData office = IconData(
    0xe837,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData garage = IconData(
    0xe838,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData laundry = IconData(
    0xe839,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData bathroom = IconData(
    0xe83a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData bedroom = IconData(
    0xe83b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData livingRoom = IconData(
    0xe83c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData kitchen = IconData(
    0xe83d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData chevronUp = IconData(
    0xe83e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData more = IconData(
    0xe83f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData check = IconData(
    0xe840,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData clear = IconData(
    0xe841,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData close = IconData(
    0xe842,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData minus = IconData(
    0xe843,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );

  static const IconData chevronDown = IconData(
    0xe845,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
