name: 'Setup Flutter'
description: 'Sets up Flutter and creates .env files'

runs:
  using: "composite"
  steps:
    - name: Set up Flutter
      uses: ./.github/actions/setup-flutter
      with:
        channel: stable
        cache: true

    - name: Install dependencies
      shell: bash
      run: flutter pub get
      working-directory: alfie_flutter
