name: 'Setup Flutter'
description: 'Sets up Flutter and creates .env files'

runs:
  using: "composite"
  steps:
    - name: Set up Flutter
      uses: ./.github/actions/setup-flutter
      with:
        channel: stable
        cache: true
          
    - name: Create .env files from secrets
      shell: bash
      run: |
          echo "" > .env.dev
          echo "" > .env.prod
      working-directory: alfie_flutter

    - name: Install dependencies
      shell: bash
      run: flutter pub get
      working-directory: alfie_flutter
