targets:
  $default:
    builders:
      graphql_codegen:
        options:
          outputDirectory: /lib/graphql/generated
          assetsPath: lib/graphql/**.graphql
          clients:
              - graphql_flutter