targets:
  $default:
    builders:
      graphql_codegen:
        options:
          scalars:
              URL:
                type: String!
          outputDirectory: /lib/graphql/generated
          assetsPath: lib/graphql/**.graphql
          clients:
              - graphql_flutter