name: 'Setup Flutter'
description: 'Sets up Flutter and creates .env files'

runs:
  using: "composite"
  steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@0ca7a949e71ae44c8e688a51c5e7e93b2c87e295 # v2.22.0
      with:
        channel: stable
          
    - name: Create .env files from secrets
      shell: bash
      run: |
          echo "${{ env.ENV_DEV }}" > .env.dev
          echo "${{ env.ENV_PROD }}" > .env.prod
      working-directory: alfie_flutter

    - name: Install dependencies
      shell: bash
      run: flutter pub get
      working-directory: alfie_flutter