name: CI

on:
  push:
    branches-ignore: [main, "release/**"]
  pull_request:

jobs:
  test-and-lint:
    uses: ./.github/workflows/test-and-lint.yaml
    inputs:
      run-smoke-tests: ${{ github.event_name == 'pull_request' }}
    secrets:
      ENV_DEV: ${{ secrets.ENV_DEV }}
      ENV_PROD: ${{ secrets.ENV_PROD }}