name: CI

on:
  push:
    branches-ignore: [main, "release/**"]
  pull_request:

jobs:
  test-and-lint:
    uses: ./.github/workflows/test-and-lint.yaml
    with:
      run-smoke-tests: ${{ github.event_name == 'pull_request' }}