name: Test and Lint

on:
  workflow_call:
    inputs:
      run-smoke-tests:
        description: 'Whether to run integration smoke tests'
        default: true
        type: boolean 

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Linting
        run: flutter analyze
        working-directory: alfie_flutter

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@6c1aa0cc9e1c02f9f58f01ac599f1064ccc83470
        with:
          ref: v2.4

      - name: Run tests
        run: ./test_coverage.sh
        working-directory: alfie_flutter

      - name: Enable KVM
        if: ${{ inputs.run-smoke-tests }}
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run Smoke Integration Tests
        if: ${{ inputs.run-smoke-tests }}
        uses: reactivecircus/android-emulator-runner@e89f39f1abbbd05b1113a29cf4db69e7540cae5a
        with:
          api-level: 30
          arch: x86_64
          profile: pixel_7_pro
          enable-hw-keyboard: true
          script: |
            cd alfie_flutter && flutter test integration_test --tags=smoke

      - name: Report LCOV
        uses: zgosalvez/github-actions-report-lcov@84f16a83ae03e846a4c697bd75cae3f94fa9f426
        with:
          coverage-files: alfie_flutter/coverage/lcov.info
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: alfie_flutter
          genhtml-ignore-errors: inconsistent,inconsistent,empty